const teams = {
	vvik: "Västervik",
	vlh: "Växjö Lakers",
	vik: "Västerås",
	tik: "Timrå",
	taif: "Tingsryd",
	ssk: "Södertälje",
	ske: "Skellefteå",
	rbk: "Rögle",
	öik: "Östersund",
	öhk: "Örebro",
	mik: "Malmö Redhawks",
	modo: "MoDO",
	mif: "Mora",
	lif: "Leksands IF",
	lhf: "Luleå",
	lhc: "Linköping",
	kik: "Kristianstad",
	iko: "IK Oskarshamn",
	ifb: "Björklöven",
	hv71: "HV71",
	fhc: "Frölunda",
	fbk: "Färjestad",
	dif: "Djurgården",
	bik: "BIK Karlskoga",
	bif: "Brynäs",
	ais: "Almtuna",
	aik: "AIK",
	vit: "Vita Hästen"
};

export { teams };
